name: bootstrap-sortable

on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up npmrc
        run: echo "//npm.pkg.github.com/:_authToken=${{ secrets.NPM_GITHUB_TOKEN }}" > .npmrc
      - run: npm install
      - name: Install PhantomJS
        run: chmod +x install_phantomjs.sh && bash install_phantomjs.sh
      - run: npm build
      - run: npm ci
      - run: npm config rm proxy
      - run: npm config rm https-proxy
      - run: npm publish --access public
        env:
          NPM_CONFIG_USERCONFIG: .npmrc
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}

