name: bootstrap-sortable

on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
          scope: '@metehaansever'
      - run: npm install
      - name: Install PhantomJS
        run: chmod +x install_phantomjs.sh && bash install_phantomjs.sh
        
      - run: npm build
      - run: npm ci
      - run: npm config rm proxy
      - run: npm config rm https-proxy
      - run: npm publish --provenance --access public
        working-directory: bootstrap-sortable
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
