name: bootstrap-sortable

on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install phantomjs-prebuilt@2.1.16
      - run: npm install
      - run: npm build
      - run: npm ci
      - run: npm config rm proxy
      - run: npm config rm https-proxy
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_GITHUB_TOKEN }}
