name: bootstrap-sortable

on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registery.npmjs.org
          scope: '@metehaansever'
      - run: npm install
      - name: Install PhantomJS
        run: |
          cd /tmp && \
          curl -OL https://bitbucket.org/ariya/phantomjs/downloads/phantomjs-1.9.8-linux-x86_64.tar.bz2 && \
          tar xjf phantomjs-1.9.8-linux-x86_64.tar.bz2 phantomjs-1.9.8-linux-x86_64/bin/phantomjs && \
          mv phantomjs-1.9.8-linux-x86_64/bin/phantomjs /usr/local/bin && \
          rm -r phantomjs-1.9.8-linux-x86_64*
      - run: npm publish --access public
        working-directory: my-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
