name: bootstrap-sortable

on:
  push:
    branches:
      - master

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registery.npmjs.org
          scope: '@metehaansever'
      - run: npm install
      - name: Install PhantomJS
        run: bash install_phantomjs.sh
        
      - run: npm publish --access public
        working-directory: my-package
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_AUTH_TOKEN}}
